# Generated by Django 3.0.2 on 2020-02-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.SimpleCourse')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleDayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daytime_day', to='scheduler.SimpleDay')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daytime_time', to='scheduler.SimpleTime')),
            ],
        ),
        migrations.AddField(
            model_name='simplecourse',
            name='times',
            field=models.ManyToManyField(blank=True, related_name='course_times', to='scheduler.SimpleDayTime'),
        ),
    ]
