# Generated by Django 3.0.2 on 2020-02-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_complexcourse_complexdepartment_complexinstructor_complexmeetingtime_complexroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complexmeetingtime',
            old_name='name',
            new_name='code',
        ),
    ]
