# Generated by Django 3.0.2 on 2020-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200202_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.ManyToManyField(blank=True, related_name='assigned_times', to='scheduler.SimpleDayTime')),
            ],
        ),
        migrations.RemoveField(
            model_name='simplecourse',
            name='times',
        ),
        migrations.CreateModel(
            name='SimpleSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('assignments', models.ManyToManyField(blank=True, related_name='schedule_assignment', to='scheduler.SimpleCourseAssignment')),
            ],
        ),
    ]
