# Generated by Django 3.0.2 on 2020-02-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20200204_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplecourseassignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scheduler.SimpleCourse'),
            preserve_default=False,
        ),
    ]
