# Generated by Django 3.0.2 on 2020-02-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_simplecourseassignment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ComplexCourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ComplexInstructor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ComplexMeetingTime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.ComplexRoom')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='schedule_classes', to='scheduler.ComplexClass')),
            ],
        ),
    ]
